apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: 'argoproj.io'
    kind: 'Application'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
