apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: counter
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: counter
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/ondrejsika/counter.git
    targetRevision: v0.5.0
    path: ./charts/counter
    helm:
      valuesObject:
        host: counter.k8s.sikademo.com
        image: ghcr.io/ondrejsika/counter:v0.5.0
